// Build script — copy src/ to dist/ and zip it for Chrome Web Store submission.
//
// Modes:
//   node scripts/build.mjs                 → prod (default)
//   node scripts/build.mjs --env=prod      → prod
//   node scripts/build.mjs --env=local     → points at https://tools.zerethon.local:7890,
//                                            appends "(DEV)" to the extension name,
//                                            adds an orange DEV bar to the launcher
//
// Whitelist over blacklist: only files listed below ship. A stray .DS_Store or
// accidentally-committed .env can never reach the store package.

import { promises as fs } from 'node:fs';
import { execFile } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const SRC = path.join(ROOT, 'src');
const DIST = path.join(ROOT, 'dist');

const ENV_ARG = process.argv.find((a) => a.startsWith('--env='));
const ENV = ENV_ARG ? ENV_ARG.split('=')[1] : 'prod';
if (!['prod', 'local'].includes(ENV)) {
  console.error(`Unknown --env=${ENV}. Use prod or local.`);
  process.exit(1);
}

const ENVS = {
  prod: {
    baseUrl: 'https://tools.zerethon.com',
    nameSuffix: '',
    isDev: false,
  },
  local: {
    baseUrl: 'https://tools.zerethon.local:7890',
    nameSuffix: ' (DEV)',
    isDev: true,
  },
};
const CFG = ENVS[ENV];

const INCLUDE = [
  'manifest.json',
  'background.js',
  'popup/popup.html',
  'popup/popup.js',
  'popup/popup.css',
  'sidepanel/sidepanel.html',
  'sidepanel/sidepanel.js',
  'sidepanel/sidepanel.css',
  'lib/config.js',
  'lib/tools-registry.js',
  'lib/recents.js',
  'lib/favorites.js',
  'lib/launcher.js',
  'icons/icon16.png',
  'icons/icon48.png',
  'icons/icon128.png',
  '_locales/en/messages.json',
  '_locales/vi/messages.json',
  // v0.2 bundled offline tools — shared shell + per-tool pages
  'tools/_shell/shell.css',
  'tools/_shell/shell.js',
  'tools/_shell/icons.js',
  'tools/json-formatter/index.html',
  'tools/json-formatter/tool.js',
  'tools/base64-encoder/index.html',
  'tools/base64-encoder/tool.js',
  'tools/hash-generator/index.html',
  'tools/hash-generator/tool.js',
];

async function main() {
  await fs.rm(DIST, { recursive: true, force: true });
  await fs.mkdir(DIST, { recursive: true });

  for (const rel of INCLUDE) {
    const from = path.join(SRC, rel);
    const to = path.join(DIST, rel);
    await fs.mkdir(path.dirname(to), { recursive: true });
    await fs.copyFile(from, to);
  }

  await rewriteConfig();
  await rewriteManifest();
  await rewriteLocales();

  const manifest = JSON.parse(await fs.readFile(path.join(DIST, 'manifest.json'), 'utf8'));
  const version = manifest.version;
  const tag = ENV === 'local' ? '-dev' : '';
  const zipName = `zerethon-tools-v${version}${tag}.zip`;
  const zipPath = path.join(ROOT, zipName);
  await fs.rm(zipPath, { force: true });

  await new Promise((resolve, reject) => {
    execFile('zip', ['-r', '-X', zipPath, '.'], { cwd: DIST }, (err) => err ? reject(err) : resolve());
  });

  const stat = await fs.stat(zipPath);
  console.log(`✓ env=${ENV}  base=${CFG.baseUrl}`);
  console.log(`✓ Built ${INCLUDE.length} files → ${path.relative(ROOT, zipPath)} (${(stat.size / 1024).toFixed(1)} KB)`);
  console.log(`  Load unpacked: chrome://extensions → Developer Mode → Load Unpacked → ${path.relative(ROOT, DIST)}/`);
}

async function rewriteConfig() {
  const p = path.join(DIST, 'lib/config.js');
  const next =
`// Generated by scripts/build.mjs --env=${ENV}. Do not edit by hand in dist/.
export const BASE_URL = ${JSON.stringify(CFG.baseUrl)};
export const API_URL = \`\${BASE_URL}/api/internal/tools.json\`;
export const IS_DEV = ${CFG.isDev};
`;
  await fs.writeFile(p, next, 'utf8');
}

async function rewriteManifest() {
  const p = path.join(DIST, 'manifest.json');
  const m = JSON.parse(await fs.readFile(p, 'utf8'));
  m.host_permissions = [`${CFG.baseUrl}/*`];
  m.content_security_policy = {
    extension_pages: `script-src 'self'; object-src 'self'; connect-src 'self' ${CFG.baseUrl}`,
  };
  await fs.writeFile(p, JSON.stringify(m, null, 2) + '\n', 'utf8');
}

async function rewriteLocales() {
  if (!CFG.nameSuffix) return;
  const localesDir = path.join(DIST, '_locales');
  const dirs = await fs.readdir(localesDir);
  for (const d of dirs) {
    const file = path.join(localesDir, d, 'messages.json');
    const msgs = JSON.parse(await fs.readFile(file, 'utf8'));
    if (msgs.ext_name?.message && !msgs.ext_name.message.endsWith(CFG.nameSuffix)) {
      msgs.ext_name.message += CFG.nameSuffix;
    }
    await fs.writeFile(file, JSON.stringify(msgs, null, 2) + '\n', 'utf8');
  }
}

main().catch((e) => { console.error(e); process.exit(1); });
